import fs from 'node:fs';
import path from 'node:path';

const actors = [
    ['chotot-listings','Authorized Vietnam Classifieds Export Normalizer','VIETNAM CLASSIFIEDS','#22D3EE','#F59E0B'],
    ['jobs-ch-swiss','Authorized Swiss Job Export Normalizer','SWISS JOB EXPORTS','#EF4444','#F8FAFC'],
    ['layoff-tracker','Authorized Workforce Event Evidence Normalizer','WORKFORCE EVENTS','#A78BFA','#38BDF8'],
    ['rug-pull-scorer','Authorized Token Risk Evidence Normalizer','TOKEN RISK EVIDENCE','#34D399','#FBBF24'],
    ['storia-bucharest','Authorized Bucharest Property Export Normalizer','BUCHAREST PROPERTY','#F97316','#60A5FA'],
];
const x=(v)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const shell=(title,market,a,b,workflow=false)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#07111F"/><stop offset="1" stop-color="#17213A"/></linearGradient><linearGradient id="accent"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="1600" height="900" fill="url(#bg)"/><circle cx="1440" cy="80" r="260" fill="${a}" opacity=".12"/><text x="76" y="90" fill="${a}" font-family="Inter,Arial" font-size="21" font-weight="700" letter-spacing="4">${x(market)}</text><text x="76" y="180" fill="#fff" font-family="Inter,Arial" font-size="54" font-weight="750">${x(workflow?'Rights-to-settlement workflow':title)}</text><text x="78" y="238" fill="#B9CAE7" font-family="Inter,Arial" font-size="27">${x(workflow?title:'Authorized records in · review-ready evidence out')}</text>${workflow?workflowBody(a,b):heroBody(a,b)}<text x="1520" y="850" text-anchor="end" fill="#8195B5" font-family="Inter,Arial" font-size="19">ZININ DATA PRODUCTS · APIFY</text></svg>`;
const heroBody=(a,b)=>`<rect x="76" y="292" width="1448" height="3" fill="url(#accent)"/><g font-family="Inter,Arial"><rect x="76" y="350" width="420" height="310" rx="28" fill="#13233D" stroke="${a}" stroke-width="2"/><text x="112" y="414" fill="${a}" font-size="21" font-weight="700">AUTHORIZED INPUT</text><text x="112" y="478" fill="#F5F8FF" font-size="27">Stable record identity</text><text x="112" y="527" fill="#F5F8FF" font-size="27">Rights &amp; provenance</text><text x="112" y="576" fill="#F5F8FF" font-size="27">Bounded source facts</text><rect x="590" y="350" width="420" height="310" rx="28" fill="#13233D" stroke="${b}" stroke-width="2"/><text x="626" y="414" fill="${b}" font-size="21" font-weight="700">ZERO-NETWORK NORMALIZATION</text><text x="626" y="478" fill="#F5F8FF" font-size="27">Validate &amp; dedupe</text><text x="626" y="527" fill="#F5F8FF" font-size="27">Freshness &amp; gaps</text><text x="626" y="576" fill="#F5F8FF" font-size="27">Evidence digest</text><rect x="1104" y="350" width="420" height="310" rx="28" fill="#13233D" stroke="${a}" stroke-width="2"/><text x="1140" y="414" fill="${a}" font-size="21" font-weight="700">CURRENT-RUN OUTCOME</text><text x="1140" y="478" fill="#F5F8FF" font-size="27">Dataset review row</text><text x="1140" y="527" fill="#F5F8FF" font-size="27">Exact named +1</text><text x="1140" y="576" fill="#F5F8FF" font-size="27">Human action only</text></g><text x="78" y="748" fill="#AFC1DF" font-family="Inter,Arial" font-size="23">No portal · no provider · no browser · no inference · safeToAutomate=false</text>`;
const workflowBody=(a,b)=>{const s=[['1','RIGHTS','Confirm permitted use'],['2','SCHEMA','Validate closed record'],['3','IDENTITY','Dedupe stable IDs'],['4','EVIDENCE','Bind source &amp; gaps'],['5','SETTLEMENT','Prove named +1'],['6','REVIEW','Human action only']];return `<g font-family="Inter,Arial">${s.map((v,i)=>{const left=58+i*254,c=i%2?a:b;return `<rect x="${left}" y="350" width="220" height="285" rx="25" fill="#13233D" stroke="${c}" stroke-width="2"/><circle cx="${left+42}" cy="397" r="23" fill="${c}" opacity=".2"/><text x="${left+42}" y="405" text-anchor="middle" fill="${c}" font-size="20" font-weight="800">${v[0]}</text><text x="${left+24}" y="470" fill="${c}" font-size="20" font-weight="700">${v[1]}</text><text x="${left+24}" y="530" fill="#F4F8FF" font-size="22">${v[2]}</text>${i<5?`<path d="M${left+220} 494h34" stroke="#6B82A7" stroke-width="4"/>`:''}`;}).join('')}</g><rect x="58" y="690" width="1480" height="82" rx="23" fill="#0F1E37" stroke="${a}"/><text x="92" y="741" fill="#EAF2FF" font-family="Inter,Arial" font-size="23">Dataset carries settlement-neutral evidence · KVS OUTPUT carries authoritative current-run settlement</text>`;};
for(const [slug,title,market,a,b] of actors){const dir=path.join(process.cwd(),'commercial115',slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'readme-hero.svg'),shell(title,market,a,b));fs.writeFileSync(path.join(dir,'readme-workflow.svg'),shell(title,market,a,b,true));}
console.log(JSON.stringify({generated:actors.map(a=>a[0]),dimensions:'1600x900'},null,2));
